# Generated by Django 4.0.1 on 2022-02-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakingnews',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
