# Generated by Django 4.0.1 on 2022-02-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0002_breakingnews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
