# Generated by Django 4.0.1 on 2022-02-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderitems',
            new_name='orderproduct',
        ),
    ]
