# Generated by Django 4.0.1 on 2022-02-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_App', '0004_confirmproduct'),
        ('Employee_App', '0002_rename_item_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='Seller_App.products'),
        ),
    ]
