# Generated by Django 4.0.1 on 2022-02-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
