# Generated by Django 4.0.1 on 2022-02-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_App', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
