# Generated by Django 4.0.1 on 2022-02-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_App', '0003_news_hide_news_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
