# Generated by Django 4.0.1 on 2022-02-08 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Seller_App', '0003_products_address_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_product', to='Seller_App.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='del_man', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
