# Generated by Django 4.0.1 on 2022-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_App', '0004_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
