# Generated by Django 4.0.1 on 2022-02-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='nid_number',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
