# Generated by Django 4.0.1 on 2022-02-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0002_adminprofile_employeeprofile_sellerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='address_1',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='address_1',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='address_1',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
